Numpy

In [3]:
import numpy as np

In [6]:
# create array using numpy
# create 1D array
arr1 = np.array([1,2,3,4,5]) 
# np.array() is a function which will actually help us to create an array.
# and inside this , I can give list or tuple
print(arr1)
print(type(arr1))
print(arr1.shape) # whenever there is a single dimension, only one number will be available.
# No specific rows or columns are there 
# Its just treated as a single dimension with 5 elements.

# single dimension array is basically having one braces entry and one braces closing.

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # means 1 row and 5 columns.
# Here is we can see two braces is getting open and two braces is getting closed.
# so this becomes a two dimensional array.

array([[1, 2, 3, 4, 5]])

In [8]:
# If i go ahead and reshape it in 1,4
arr2.reshape(1,4)
# It will raise ValueError because it will not work because there are 5 elements , 
# how can i reshape to 1,4 !

ValueError: cannot reshape array of size 5 into shape (1,4)

In [8]:
# Can we go and create two dimension array directly?
# Yes
arr2 = np.array([[1,2,3,4,5]]) # using nested list(use list within a list)
arr2.shape

(1, 5)

In [12]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape) # 2 rows and 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [23]:
print(np.arange(0,10,2)) # single dimension array or 5 elements (no row , no column)
print(np.arange(0,10,2).reshape(5,1)) # Reshape or converted 1d to 2d array

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


Inbuilt functions present in numpy array

In [24]:
np.ones((3,4)) 
# It means 2 d array with 3 rows and 4 columns
# and all the elements are going to be one.

# Why we have this function ?
# When we see in deep learning, some of the inbuilt functions of numpy like np.ones or np.zeros
# lets say I have to initialize the initial weights to zero.
# I can directly use this inbuilt function and create it over there.
# quickly it helps us to create all these elements otherwise i had to write multiple list over here.
# then probably convert into numpy array.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# Identity Matrix
np.eye(3)

# What is Identity matrix?
# Its like all the diagonal elements will be one remaining all will be zero

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print('Array:\n', arr)
print('Shape: ',arr.shape)
print('Number of dimensions: ',arr.ndim)
print('Size (Number of elements):', arr.size)
print('Data type: ', arr.dtype)
print('item size (in bytes):', arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (Number of elements): 6
Data type:  int64
item size (in bytes): 8


In [36]:
# Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([12,13,14,15,16])

# Elements wise addition
print('Addition:', arr1+arr2)

# Elements wise Substraction
print('Substraction:', arr1 - arr2)

# Elements wise multiplication
print('Multiplication: ', arr1 * arr2)

# Elements wise Division
print('Division:', arr1/arr2)

Addition: [13 15 17 19 21]
Substraction: [-11 -11 -11 -11 -11]
Multiplication:  [12 26 42 60 80]
Division: [0.08333333 0.15384615 0.21428571 0.26666667 0.3125    ]


In [38]:
# Universal Function
arr = np.array([2,3,4,5,6])
# Square root 
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# Sine
print(np.sin(arr))
# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [40]:
# array slicing and Indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print('Array: \n',arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [45]:
# index start from 0
print(arr[0][0])

1


In [44]:
# how can we access 7,8,9 and 12,13,14 ?

arr[1:,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [46]:
# How can we access 3,4,5 and 8,9,10?
arr[0:2,2:5] 

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [54]:
print(arr[0:,2:])

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [56]:
# Modify array elements
arr[0,0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [57]:
arr[1:] = 100
arr

array([[100,   2,   3,   4,   5],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [61]:
# Statistical Concepts - Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
Normalized_data = (data - mean) /std_dev
print(f'Normalized_data: {Normalized_data}')

Normalized_data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [67]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
# Mean
mean = np.mean(data)
print('Mean:',mean)
# Median
median = np.median(data)
print('Median:',median)
# Standard deviation
std_dev = np.std(data)
print('standard deviation:',std_dev)
# Variance
variance = np.var(data)
print('Variance:', variance)

Mean: 5.5
Median: 5.5
standard deviation: 2.8722813232690143
Variance: 8.25


In [69]:
# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data >5
# It is going to give me an array which says whichever value is greater than 5 that will be true.
# whichever value is less than 5 will give me false
# So it is applying a condition on this particular data 


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
# lets say that i just want to retrieve all those elements that are greater than 5
# So all I have to do indexing where i say data of data greater than 5
data[data>5]

array([ 6,  7,  8,  9, 10])

In [73]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])