# Module: NumPy Assignments
## Lesson: NumPy



In [2]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20.
#  Replace all the elements in the third column with 1.


import numpy as np
import random 
arr1 =np.random.randint(1,21,size=(5,5))
print(arr1)
print('Original array')

arr1[:,2]=1
print(arr1)
print('Manipulated array')



[[ 6 14 20 17 11]
 [ 7  4  2 13  7]
 [10 13 16 17 17]
 [14  5  9 12 11]
 [ 7 17  5  1 13]]
Original array
[[ 6 14  1 17 11]
 [ 7  4  1 13  7]
 [10 13  1 17 17]
 [14  5  1 12 11]
 [ 7 17  1  1 13]]
Manipulated array


In [66]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16.
#  Replace the diagonal elements with 0.
arr = np.arange(1,17).reshape(4,4)
print('Original array:')
print(arr)

np.fill_diagonal(arr,0)
print('Modified array:')
print(arr)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [67]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36.
#  Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


array = np.arange(1,37).reshape(6,6)
print('Original array')
print(array)

sub_array = array[2:5,1:4]
print('Sub-Array')
print(sub_array)

Original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-Array
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [5]:
# 2. Create a NumPy array of shape (5, 5) with random integers.
#  Extract the elements on the border.
arr = np.random.randint(1,21,size=(5,5))
print(arr)
#print(arr[0:,0])
#print(arr[0:,-1])
#print(arr[0,:])
#print(arr[-1,:])

border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
border_elements

[[14  2 16  7  5]
 [ 2  3  1  7  9]
 [10 20  9 13  4]
 [19 18  9  1 20]
 [ 1  8 15  4 17]]


array([14,  2, 16,  7,  5,  1,  8, 15,  4, 17,  2, 10, 19,  9,  4, 20],
      dtype=int32)

In [109]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers.
# Perform element-wise addition, subtraction, multiplication, and division.

arr1 = np.random.randint(1,21,size=(3,4))
arr2 = np.random.randint(1,21,size=(3,4))
print(arr1)
print(arr2)
addi = np.add(arr1,arr2)
print(f'Addition: {addi}')
sub = np.subtract(arr1,arr2)
print(f'Subtraction: {sub}')
mul = np.multiply(arr1,arr2)
print(f'Multiplication: {mul}')
div = np.divide(arr1,arr2)
print(f'division: {div}')


[[ 7 20 10  6]
 [ 7  6 13 20]
 [14 12 19  2]]
[[17 16 20  7]
 [ 9  6  3 10]
 [ 7 10  9  4]]
Addition: [[24 36 30 13]
 [16 12 16 30]
 [21 22 28  6]]
Subtraction: [[-10   4 -10  -1]
 [ -2   0  10  10]
 [  7   2  10  -2]]
Multiplication: [[119 320 200  42]
 [ 63  36  39 200]
 [ 98 120 171   8]]
division: [[0.41176471 1.25       0.5        0.85714286]
 [0.77777778 1.         4.33333333 2.        ]
 [2.         1.2        2.11111111 0.5       ]]


In [114]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16.
# Compute the row-wise and column-wise sum.
arr = np.arange(1,17).reshape(4,4)
row = np.sum(arr,axis=1)
col = np.sum(arr,axis=0)
print('Array:')
print(arr)
print(f'row-wise sum :{row}')
print(f'col-wise sum: {col}')

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row-wise sum :[10 26 42 58]
col-wise sum: [28 32 36 40]


In [121]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers.
#  Compute the mean, median, standard deviation, and variance of the array.
arr = np.random.randint(1,21,size= (5,5))
print(f'Array: {arr}')
print(f'Mean: {np.mean(arr)}')
print(f'Median: {np.median(arr)}')
print(f'standard deviation: {np.std(arr)}')
print(f'variance: {np.var(arr)}')

Array: [[11  2 20 17 16]
 [ 2 15  9 16 14]
 [ 5 19  4 16 14]
 [ 8  5 20  3  6]
 [18  8 13  8  6]]
Mean: 11.0
Median: 11.0
standard deviation: 5.837807807730569
variance: 34.08


In [126]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr = np.arange(1,10).reshape(3,3)
print(arr)
mean = np.mean(arr)
std_dev = np.std(arr)
print(f'std: {std_dev}')
normalized_array = (arr -mean)/std_dev
normalized_array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
std: 2.581988897471611


array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [130]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr = np.random.randint(1,21,size=(3,3))
row_arr = np.random.randint(1,21,size=(3,))
print(f'2D array: {arr}')
print(f'1D array: {row_arr}')
result = arr + row_arr
result


2D array: [[ 6  2 16]
 [ 8  5  5]
 [18 19  5]]
1D array: [13 14  3]


array([[19, 16, 19],
       [21, 19,  8],
       [31, 33,  8]], dtype=int32)

In [6]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers.
#  Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr1 = np.random.randint(1,21,size=(4,4))
arr2 = np.random.randint(1,21,size=(4,))
print('arr1:')
print(arr1)
print('arr2:')
print(arr2)
result = arr1-arr2[:,np.newaxis]
result

arr1:
[[20 11 17  2]
 [ 6 20  5 10]
 [16  6  9 16]
 [ 2 16  5 13]]
arr2:
[7 6 1 1]


array([[13,  4, 10, -5],
       [ 0, 14, -1,  4],
       [15,  5,  8, 15],
       [ 1, 15,  4, 12]], dtype=int32)

In [9]:
# Use of np.newaxis

print(arr2)
print(arr2[:,np.newaxis])
print(arr2[np.newaxis,:])

[7 6 1 1]
[[7]
 [6]
 [1]
 [1]]
[[7 6 1 1]]


In [17]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix.
#  Compute its determinant, inverse, and eigenvalues.


# Create a Matrix
Matrix = np.random.randint(1,10,size=(3,3))
print('Original Matrix')
print(Matrix)

# compute determinant
determinant = np.linalg.det(Matrix)
print(f'determinant: {determinant}')

# compute inverse
inverse = np.linalg.inv(Matrix)
print(f'inverse: {inverse}')
# compute eigenvalues
eigenvalues = np.linalg.eigvals(Matrix)
print(f'eigenvalues: {eigenvalues}')

Original Matrix
[[1 3 2]
 [4 6 6]
 [5 4 8]]
determinant: -10.000000000000002
inverse: [[-2.4  1.6 -0.6]
 [ 0.2  0.2 -0.2]
 [ 1.4 -1.1  0.6]]
eigenvalues: [13.78686503 -0.43901951  1.65215448]


In [22]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2).
#  Perform matrix multiplication on these arrays.
arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))
mul = np.dot(arr1,arr2)
print('arr1:')
print(arr1)
print('arr2:')
print(arr2)
print('Matrix Multiplication:')
print(mul)


arr1:
[[1 7 1]
 [9 7 1]]
arr2:
[[3 6]
 [4 2]
 [9 4]]
Matrix Multiplication:
[[40 24]
 [64 72]]


In [32]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Reshape the array to shape (1, 9) and then to shape (9, 1).

arr = np.arange(1,10).reshape(3,3)
print(arr)
arr= arr.reshape(1,9)
print(arr)
arr = arr.reshape(9,1)
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [40]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers.
#  Flatten the array and then reshape it back to (5, 5).
arr = np.random.randint(1,11,size=(5,5))
print('Original array:')
print(arr)
Flatter_arr = arr.flatten()
print('Flatter_arr:')
print(Flatter_arr)
reshaped_arr= Flatter_arr.reshape(5,5)
print('reshaped_arr:')
print(reshaped_arr)

Original array:
[[ 9  1  2 10 10]
 [ 5  4  6  8  3]
 [ 1  8  1  9  5]
 [ 8  2 10  2  3]
 [ 8  4 10  2  1]]
Flatter_arr:
[ 9  1  2 10 10  5  4  6  8  3  1  8  1  9  5  8  2 10  2  3  8  4 10  2
  1]
reshaped_arr:
[[ 9  1  2 10 10]
 [ 5  4  6  8  3]
 [ 1  8  1  9  5]
 [ 8  2 10  2  3]
 [ 8  4 10  2  1]]


In [47]:
### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers.
#  Use fancy indexing to extract the elements at the corners of the array.

arr = np.random.randint(1,11,size=(5,5))
print('array:')
print(arr)
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print('corners:')
print(corners)

array:
[[ 4  6  8  7  9]
 [ 1  5  8 10  8]
 [ 8  8  6  1  8]
 [ 3  6  1 10  2]
 [ 4  2  7 10  5]]
corners:
[4 9 4 5]


In [57]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.
arr = np.random.randint(1,21,size=(4,4))
print('Original array')
print(arr)

arr[arr>10]=10
print('Modified array:')
print(arr)

Original array
[[17 15 16 13]
 [14 19 14 12]
 [ 5 15 13 14]
 [14  4 19  6]]
Modified array:
[[10 10 10 10]
 [10 10 10 10]
 [ 5 10 10 10]
 [10  4 10  6]]


In [65]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float).
#  Add some data and sort the array by age.

data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('keshav',25,70),('papa',52,85),('mummy',46,65)],dtype=data_type)
print('Original array:')
print(data)


sorted_data= np.sort(data,order='age')
print('Sorted array:')
print(sorted_data)

Original array:
[('keshav', 25, 70.) ('papa', 52, 85.) ('mummy', 46, 65.)]
Sorted array:
[('keshav', 25, 70.) ('mummy', 46, 65.) ('papa', 52, 85.)]


In [76]:
# 2. Create a structured array with fields 'x' and 'y' (both integers).
# Add some data and compute the Euclidean distance between each pair of points.
data_type=[('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)],dtype=data_type)
print('array:')
print(data)

euclidean = np.sqrt((data['x'][:,np.newaxis]-data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print('Euclidean distance:')
print(euclidean)

array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distance:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [88]:
### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and
#  mask the elements greater than 10.
#  Compute the sum of the unmasked elements.
import numpy.ma as ma
arr = np.random.randint(1,21,size=(4,4))
print('original array:')
print(arr)
masked_arr = ma.masked_greater(arr,10)
print('masked array:')
print(masked_arr)

sum_unmasked = masked_arr.sum()
print(f'sum of unmasked array: {sum_unmasked}')

original array:
[[ 4 13 11 18]
 [19 15 14 10]
 [14 16 19  5]
 [15 16  4  1]]
masked array:
[[4 -- -- --]
 [-- -- -- 10]
 [-- -- -- 5]
 [-- -- 4 1]]
sum of unmasked array: 24


In [94]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements.
#  Replace the masked elements with the mean of the unmasked elements.
arr= np.random.randint(1,11,size=(3,3))
print(arr)
masked_arr = ma.masked_array(arr,mask=np.eye(3,dtype=bool))
print(masked_arr)
mean = masked_arr.mean()
print(mean)
unmasked_ele = masked_arr.filled(mean)
print(unmasked_ele)

[[ 2  3  7]
 [ 8 10  9]
 [ 8  8  5]]
[[-- 3 7]
 [8 -- 9]
 [8 8 --]]
7.166666666666667
[[7 3 7]
 [8 7 9]
 [8 8 7]]
